equipment/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'equipment'

urlpatterns = [
	#/equipment/
	path('', views.equipment, name='bio-app-equipment'),
	
	#/equipment/<equipmenttype_id>/ but i want it to be equipment/glasswares
	url(r'^(?P<Category_id>[0-9]+)/$', views.detail, name='bio-app-detail'),

	#/equipment/<equipmenttype_id>/<equipment_id>/
	url(r'^(?P<Category_id>[0-9]+)/(?P<Item_id>[0-9]+)/$', views.item, name='bio-app-item'),

	#/equipment/<equipmenttype_id>/favorite/
	#url(r'^(?P<EquipmentType_id>[0-9]+)/favorite/$', views.favorite, name='bio-app-favorite'),
]

#path('<int: EquipmentType_id>/', views.detail, name='bio-app-detail'),

equipment/models.py
from django.db import models
from student.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.exceptions import ObjectDoesNotExist

# Create your models here.
class EquipmentType(models.Model):
	type_of_equipment = models.CharField(max_length = 100)
	description = models.CharField(max_length=1000)
	type_of_equipment_picture = models.CharField(max_length=1000)

	def __str__(self): #specify what to print out
		return self.type_of_equipment + " - " + self.description


class Equipment(models.Model):
	size_choices = (
		('S', 'Small'),
		('M', 'Medium'),
		('L', 'Large'),
		('XL', "Extra Large"),
	)

	functional_or_not_choices = (
		('Functional', 'Functional'),
		('Non-Functional', 'Non-Functional'),
	)

	equipment_type = models.ForeignKey(EquipmentType, on_delete=models.CASCADE)
	name_of_equipment = models.CharField(max_length = 100)	
	number_of_items = models.IntegerField()
	size = models.CharField(max_length = 2, choices = size_choices, blank = True)
	functional_or_not = models.CharField(max_length = 15, choices= functional_or_not_choices, blank = True)
	equipment_picture = models.CharField(max_length = 1000)

	def __str__(self): #specify what to print out
		return self.name_of_equipment

class Cart(models.Model):
	size_choices = (
		('S', 'Small'),
		('M', 'Medium'),
		('L', 'Large'),
		('XL', "Extra Large"),
	)

	functional_or_not_choices = (
		('Functional', 'Functional'),
		('Non-Functional', 'Non-Functional'),
	)
	user_b = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
	name_of_equip = models.CharField(max_length = 100)	
	num_of_items = models.IntegerField(null=True)
	siz = models.CharField(max_length = 2, choices = size_choices, blank = True)
	function_or_not = models.CharField(max_length = 15, choices= functional_or_not_choices, blank = True)
	equip_picture = models.CharField(max_length = 1000, null=True)

	def __str__(self): #specify what to print out
		return self.name_of_equip

equipment/views.py
from django.shortcuts import render, get_object_or_404
from .models import EquipmentType, Equipment, Cart
from items.models import Category, Item, Borrow
def equipment(request):
	all_equipmentType = Category.objects.all()
	context = {'all_equipmentType': all_equipmentType}
	return render(request, 'equipment/index.html', context)

def detail(request, Category_id):
	#equipType = EquipmentType.objects.get(pk=EquipmentType_id)
	equipType = get_object_or_404(Category, pk=Category_id)
	return render(request, 'equipment/detail.html', {'equipType': equipType})

def item(request, Category_id, Item_id):
	equipment = get_object_or_404(Item, pk=Item_id)
	if request.method == 'POST':
		if request.POST.get('user_b') and request.POST.get('name_of_equip'):
			cart = Cart()
			cart.user_b = request.user
			cart.name_of_equip = request.POST.get('name_of_equip')
			cart.num_of_items = request.POST.get('num_of_items')
			cart.siz = request.POST.get('siz')
			#instance = cart.save(commit=False)
			#instance.user_b = request.user
			cart.save()
	return render(request, 'equipment/item.html', {'equipment': equipment})

def cart(request):
	user_b = request.user
	return render(request, 'equipment/cart.html', {'user_b':user_b})

equipment/templates/equipment/cart.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Home</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  
    <style>
        body{
            background-image: url("/static/home/media/science-background.png");

              min-height: 1000px;

              /* Center and scale the image nicely */
              background-position: center;
              background-repeat: no-repeat;
              background-size: cover;

              position: relative;
        }
        
        table{
            background-color: white;
            position: absolute;
            left:125px;
            top:200px;
            width:600px;
        }
        
        #cred{
            background-color: lightblue;
            position: absolute;
            width:500px;
            height:150px;
            left:125px;
            top:822px;
        }
        
        thead tr th h6 {
            font-size:5px;
        }   
        
        #news{
            background-color: Lightgray;
            position:absolute;
            width:500px;
            height:150px;
            left:700px;
            top:822px;
        }
    </style>
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="#">
                    <img src="/static/home/media/boiling_water-512.svg" alt="">Bio Lab Application
                </a>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-item nav-link active" href="{% url 'home' %}">Home</a>
                        <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                        <a class="nav-item nav-link" href="{% url 'equipment:bio-app-equipment' %}">Equipment</a>
                        <a class="nav-item nav-link" href="{% url 'cart' %}">Approved Items</a>
                        <a class="nav-item nav-link" href="{% url 'borrow' %}">Borrow</a>
                
                
                    </div>
                </div>
                <form class="form-inline">
                    
                <a class="nav-item nav-link" href="{% url 'adminlogout' %}">Logout</a>
                </form>
            
            </div>
        </nav>
    </header>

    <!--     End  -->
    <div>
        <div class="alert alert-info">Transaction / Borrowing</div>
        <form method="POST" action="">
            {% csrf_token %}
            {% load staticfiles %}
            <!--<div class="form-group pull-left">
                <label>Student Name:</label>
                <br/>
                <select class="form-control" name="student_id" id="student">
                    {% for student in students %}
                        <option value='{{ student.id }}'>{{ student.firstname }} {{ student.lastname }}</option>
                    {% endfor %}
                </select>
            </div>-->
            
            <table id="table" class="table table-stripped">
                <thead class="alert-success">
                <tr>
                    <th>Select</th>
                    <th>Picture</th>
                    <th>Item Title</th>
                    <th>Item Category</th>
                    <th>Available</th>
                    
                </tr>
                </thead>
                <tbody>
                {% for borrow in user_b.borrow_set.all %}
                    <tr>
                        <td><img  src="{{ borrow.picture.url }}" height="180" width="180" class="img-responsive" align="left"></td>
                        <td>{{ borrow.name_item }}</td>
                        
                      
                        <td>{{ borrow.borrower }}</td>
                        <td>
                            {{ borrow.date }}
                        </td>
                        
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


     </main>
    </div>
</div>
<script src="{% static 'js/jquery-2.2.3.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/datatables.min.js' %}"></script>

equipment/templates/equipment/detail.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Home</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
	<style>
		body{
			background-image: url("/static/home/media/science-background.png");

			  min-height: 1000px;

			  /* Center and scale the image nicely */
			  background-position: center;
			  background-repeat: no-repeat;
			  background-size: cover;

			  position: relative;
		}
	</style>
</head>
<body>
	<header class="site-header">
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<div class="container">
				<a class="navbar-brand" href="#">
					<img src="/static/home/media/boiling_water-512.svg" alt="">Bio Lab Application
				</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
				    <span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
					<div class="navbar-nav">
				        <a class="nav-item nav-link active" href="ProfileWelcomePage.html#Welcome">Home</a>
				        <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
				    </div>
	  			</div>
	  			<form class="form-inline">
				    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
				    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
				</form>
				<a class="nav-item nav-link" href="{% url 'log_out' %}">Logout</a>
			</div>
		</nav>
	</header>
	<main role="main" class="container">
		<div class="row">
	    	<div class="col-md-8">
	      		
	    	</div>
	    </div>
	</main>
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<div class="container">

  <!-- Page Heading -->
  <h1 class="my-4">Equipments
  </h1>
  <div class="col-lg-3">
        <div class="list-group">
            <h1 class="my-4">{{ equipType.type_of_equipment }}</h1>
        </div>
  </div>
      <!-- /.col-lg-3 -->
      <div class="col-lg-9">
        <div class="card mt-4">
        {% for equipment in equipType.equipment_set.all %}
          <div class="card-body">
            <h3 class="card-title">{{ equipType.description }}</h3>
    		<h2><a href="/equipment/{{ equipType.id }}/{{ equipment.id }}"><img class="card-img-top img-fluid" src = "{{equipment.equipment_picture}}" alt=""></a> </h2></p>		
	        <h3>{{ equipment.name }}</h3>
	       
          </div>
        </div>
        <!-- /.card -->
        {% endfor %}
      </div>
</div>
<!-- /.container -->



equipment/templates/equipment/index.html
{% extends 'home/base.html' %}

{% block content%}
{% if all_equipmentType %}
<div class="container">

  <!-- Page Heading -->
  <h1 class="my-4">Equipments
  </h1>

  <div class="row">
   {% for equipType in all_equipmentType  %}
   	<div class=" col-lg-4 col-md-3 col-sm-3 col-xs-3">
      <div class="thumbnail">
       <a href="#"><img class="card-img-top" src="{{equipType.type_of_equipment_picture}}" alt="..."></a>
        <div class="card-body">
          <h4 class="card-title">
            <a href="{% url 'equipment:bio-app-detail' equipType.id %}" class="btn btn-block btn-primary text-uppercase">{{equipType.name}}</a>
          </h4>    
        </div>
      </div>
    </div>

   {% endfor %}

  </div>
  <!-- /.row -->

</div>
<!-- /.container -->
 
{% else %}
	<h3>You don't have any available equipment.</h3>
{% endif %}

{% endblock %}



equipment/templates/equipment/item.html

<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;}

/* The Modal (background) */
.modal {
  background-color: rgba(0, 0, 0, 0.8);
  width: 100%;
  height: 100%;
  position: absolute;
  top: 0;
  display: none;
  justify-content: center;
  align-items: center;
}

/* Modal Content */
.modal-content {
  height: 300px;
  width: 500px;
  background-color: white;
  text-align: center;
  padding: 20px;
  position: relative;
  border-radius: 4px;
}

input {
	margin: 15px auto;
	display: block;
	width: 50%;
	padding: 8px;
	border: 1px solid gray;
}

/* The Close Button */
.close {
  position: absolute;
  top: 0;
  right: 10px;
  font-size: 15px;
  color: #333;
  cursor: pointer;
  &:hover {
	color: #666;
  }
}

.close:hover,
.close:focus {
  color: #000;
  text-decoration: none;
  cursor: pointer;
}
</style>
</head>
<body>

<img src = "{{equipment.equipment_picture}}">

<ol>
	<h1>{{ equipment.equipment_type}} : {{ equipment.name_of_equipment }}</h1>
	<h2>Number of items: {{ equipment.number_of_items }}</h2>
	<h2>Size: {{ equipment.size }}</h2>
	<h2>{{ equipment.functional_or_not}}</h2>
	<button id="myBtn">Add to Cart</button>
</ol>

<!-- Trigger/Open The Modal -->


<!-- The Modal -->
<div id="myModal" class="modal">

  <!-- Modal content -->
  {% load crispy_forms_tags %}
  <div class="modal-content">
    
      <div class="content-section">
          <form name="myForm" method="POST">
            <div class="close">x</div>
            {% csrf_token %}
            <input type="text" name = "user_b" value="{{ user.email }}" readonly="readonly">
            <input type="text" name = "name_of_equip" value="{{ equipment.name_of_equipment }}" readonly="readonly">
            <input type="number" name = "num_of_items" onkeyup = "validateForm()" min = "1" max = "{{ equipment.number_of_items }}">
            <input type="text" name = "siz" value="{{ equipment.size }}" readonly="readonly">
            <input type="submit" id = "but" value="Confirm">
             
          </form>
        </div>
  </div>

</div>


<script>
// Get the modal
var modal = document.getElementById('myModal');

// Get the button that opens the modal
var btn = document.getElementById("myBtn");

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

var num = document.forms["myForm"]["num_of_items"].value;

function validateForm(){
	if(num > 10){
		document.getElementById("but").disabled = true;
	}
}

num.onkeypress=function(evt){
    evt.preventDefault();
};

// When the user clicks the button, open the modal 
btn.onclick = function() {
  modal.style.display = "flex";
}

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
  modal.style.display = "none";
}

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
}
</script>

</body>
</html>